### ISSUE TITLE
executable no work

### ISSUE THREAD

**Issue by milena-kos** [Just-a-Unity-Dev/Just-a-Unity-Dev#9]
when i run the exe file it says something like "how do you want to commit oppen this md file" what how to do it run i please

**Comment by Just-a-Unity-Dev** [comment]
...what exe file????

i think you're on the wrong GH repo, this is my personal profile markdown

**Comment by milena-kos** [comment]
i dont think u understanddude when i tun ot says icant ooen an md fule how tofix

**Comment by Just-a-Unity-Dev** [comment]
....what?

you can use an editor like VS Code for live markdown preview, or simply use Notepad++ to edit it. you can't run a markdown file as it's a text format

**Comment by milena-kos** [comment]
what do oi mark down i no understand you r funny words wmagic man
